// INCLUDE FILE generated by "Pelles C for Windows, version 8.00".

#ifndef _OSASPLAB_H
#define _OSASPLAB_H

#ifdef _OSASPLAB_
#define OSASPLABAPI  __declspec(dllexport)
#else
#define OSASPLABAPI  __declspec(dllimport)
#endif /* _OSASPLAB_ */

#ifndef WINAPI
#define WINAPI  __stdcall
#endif

typedef struct tagINJECTEDPROCPARAMS {
	char *findWhat;
	char *replaceWith;
} INJECTEDPROCPARAMS, *PINJECTEDPROCPARAMS;

#endif /* _OSASPLAB_H */
